config/routes.rb
YourSenedd::Application.routes.draw do


  namespace :members do
  get 'speeches/index'
  end

  get 'advertising', to: 'advertising#new', as: 'advertising'
  post 'advertising/create', as: 'send_advertising'

  get 'data-services', to: 'messages#new', as: 'message'
  post 'messages/create', as: 'send_message'

  mount MountainView::Engine => "/styles"

  devise_for :users
  root :to => "dashboard#index"

  resources :debates, only: [:index, :show]
  resources :videos, only: [:show]
  resources :pending_debates, only: [:index, :create]
  resources :members, only: [:show, :index, :edit, :update]
  resources :representations

  scope module: 'members' do
    resources :members, only: [] do
      resources :speeches, only: [:index], on: :member
    end
  end

  resources :search, only: [:index]
  resources :weekly, only: [:index]
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!, except: :index

  def index
    @debates = Debate.all
    @debates_days = @debates.group_by { |a| a.log_date.to_date }
    @members = Member.random(10)
  end
end

app/views/dashboard/index.html.erb
<% title t('your_senedd') %>

<section id="recent-debates">
  <h1><%= link_to t('.recent_debates'), debates_path %></h1>
  <% @debates_days.sort.last(3).reverse!.each do |day, debates| %>
    <div class="day">
      <h2><%= I18n.l day, format: :long %></h2>
      <ul>
        <% debates.take(3).each do |debate| %>
          <li><%= link_to locale_method(debate.name, debate.name_cy), debate %></li>
        <% end %>
      </ul>
      <%= link_to t('.more_from', date: l(day, format: :short)).html_safe, debates_path + "##{day.to_s}", :class => "more" if debates.size > 5 %>
    </div>
  <% end %>
</section>

<div id="feature">
  <h1><%= t('.current_ams') %></h1>
  <ul>
    <% @members.each do |member| %>
      <li>
        <%= link_to member.name, member_path(member) %>
        <span class="constituency"><%= locale_method(member.constituency.name, member.constituency.name_cy) %></span>
      </li>
    <% end %>
    <li>
  </ul>
</div>