config/routes.rb
YourSenedd::Application.routes.draw do


  namespace :members do
  get 'speeches/index'
  end

  get 'advertising', to: 'advertising#new', as: 'advertising'
  post 'advertising/create', as: 'send_advertising'

  get 'data-services', to: 'messages#new', as: 'message'
  post 'messages/create', as: 'send_message'

  mount MountainView::Engine => "/styles"

  devise_for :users
  root :to => "dashboard#index"

  resources :debates, only: [:index, :show]
  resources :videos, only: [:show]
  resources :pending_debates, only: [:index, :create]
  resources :members, only: [:show, :index, :edit, :update]
  resources :representations

  scope module: 'members' do
    resources :members, only: [] do
      resources :speeches, only: [:index], on: :member
    end
  end

  resources :search, only: [:index]
  resources :weekly, only: [:index]
end

app/models/representation.rb
# Defines the period a Member was elected to a Constituency
class Representation < ActiveRecord::Base
  belongs_to :member
  belongs_to :constituency
end

app/controllers/representations_controller.rb
class RepresentationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @representations = Representation.where(end_log_date: nil)
  end

  def new
    @representation = Representation.new
  end

  def create
    @representation = Representation.new(representation_params)
    @representation.save

    redirect_to representations_path
  end

  def edit
    @representation = Representation.find(params[:id])
  end

  def update
    @representation = Representation.find(params[:id])
    @representation.update_attributes(representation_params)

    redirect_to representations_path
  end

  protected

  def representation_params
    params.require(:representation).permit(:member_id, :constituency_id, :log_date, :end_log_date)
  end
end

app/views/representations/_form.html.erb
<%= form_for @representation do |f| %>
  <p>
    <%= f.collection_select(:member_id, Member.all, :id, :name, prompt: true) %>
  </p>
  <p>
    <%= f.collection_select(:constituency_id, Constituency.all, :id, :name, prompt: true) %>
  </p>
  <p>
    <%= f.date_field(:log_date, value: (@representation.log_date || '2016-05-05')) %>
  </p>

  <p>
    <%= f.date_field(:end_log_date, value: (@representation.end_log_date || '2016-05-04')) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/representations/edit.html.erb
<%= render 'form' %>

app/views/representations/index.html.erb
<% @representations.each do |r| %>
  <p>
    <%= link_to edit_representation_path(r) do %>
      <%= r.member.name %> represents <%= r.constituency.name %>: <%= r.log_date %> - <%= r.end_log_date %>
    <% end %>
  </p>
<% end %>

app/views/representations/new.html.erb
<%= render 'form' %>