config/routes.rb
YourSenedd::Application.routes.draw do


  namespace :members do
  get 'speeches/index'
  end

  get 'advertising', to: 'advertising#new', as: 'advertising'
  post 'advertising/create', as: 'send_advertising'

  get 'data-services', to: 'messages#new', as: 'message'
  post 'messages/create', as: 'send_message'

  mount MountainView::Engine => "/styles"

  devise_for :users
  root :to => "dashboard#index"

  resources :debates, only: [:index, :show]
  resources :videos, only: [:show]
  resources :pending_debates, only: [:index, :create]
  resources :members, only: [:show, :index, :edit, :update]
  resources :representations

  scope module: 'members' do
    resources :members, only: [] do
      resources :speeches, only: [:index], on: :member
    end
  end

  resources :search, only: [:index]
  resources :weekly, only: [:index]
end

app/controllers/advertising_controller.rb
class AdvertisingController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :create]

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      InterestNotifier.send_advert_request(@message).deliver_now
      redirect_to advertising_path, notice: "Thank you for your interest in advertising with us."
    else
      flash[:alert] = "Please fill in all fields"
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/views/advertising/new.html.erb
<% title "Advertising | Your Senedd" %>

<section id="debates">
  <h1>Advertise with Your Senedd</h1>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
  <p>Your Senedd is creating highly engaging information between the website and <a href="/weekly">weekly newsletter</a>.</p>
  <p>Among our subscribers are CEOs of charities and private sector organisations as well as politicians and those who make change in Wales. By advertising your campaign, organisation or job with us you'll be attratcing the attention of the right people.</p>
  <p>Our website receives over 7,500 unique visitors and our email excels way above other newsletters with an open rate of 46% and click rate of 11%</p>

  <div class="error">
    <%= flash[:alert] %>
  </div>
  <%= form_for @message, url: send_advertising_path do |message_form| %>
    <fieldset>
      <div class="field">
        <%= message_form.text_field :name, placeholder: "Name" %>
      </div>

      <div class="field">
        <%= message_form.email_field :email, placeholder: "Email"%>
      </div>

      <div class="field">
        <%= message_form.text_area :content, placeholder: "Message"%>
      </div>
    </fieldset>

    <fieldset>
      <div class="field">
        <%= message_form.submit "Send" %>
      </div>
    </fieldset>
  <% end %>
</section>