config/routes.rb
YourSenedd::Application.routes.draw do


  namespace :members do
  get 'speeches/index'
  end

  get 'advertising', to: 'advertising#new', as: 'advertising'
  post 'advertising/create', as: 'send_advertising'

  get 'data-services', to: 'messages#new', as: 'message'
  post 'messages/create', as: 'send_message'

  mount MountainView::Engine => "/styles"

  devise_for :users
  root :to => "dashboard#index"

  resources :debates, only: [:index, :show]
  resources :videos, only: [:show]
  resources :pending_debates, only: [:index, :create]
  resources :members, only: [:show, :index, :edit, :update]
  resources :representations

  scope module: 'members' do
    resources :members, only: [] do
      resources :speeches, only: [:index], on: :member
    end
  end

  resources :search, only: [:index]
  resources :weekly, only: [:index]
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def show
    day = find_day(params[:id])
    @speech = find_speech(day, params[:timestamp])
  end

  private

  def video_params
    params.permit(:id, :timestamp, :autostart, :captions)
  end

  def find_day(code)
    if I18n.locale == :en
      Debate.find_by(tv: code).log_date
    else
      Debate.find_by(tv_cy: code).log_date
    end
  end

  def find_speech(day, timestamp = nil)
    if timestamp
      Speech.find_by(log_date: day, spoke_at: DateTime.parse(timestamp).in_time_zone)
    else
      Speech.find_by(log_date: day)
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/show.html.erb
<article id="debate">
  <div class="video-page">
    <div class="video">
      <img class="placeholder" src="//placehold.it/16x9"/>
      <iframe src='<%= "http://player.nafw.cloud.vualto.com/Player/Index/#{ params[:id] }?inPointUTC=#{ URI.encode(@speech.spoke_at.to_s) }&autostart=false&captionsOn=true" %>' class="video-player" name="NAFW Player" seamless="seamless" allowfullscreen>Loading video…</iframe>
    </div>
    <%= link_to 'Read transcript', debate_path(@speech.debate) + "##{@speech.id}" %>
  </div>
</article>

app/views/videos/show.js.erb
$("#video-widget").html("<%= escape_javascript(render partial: 'application/video', locals: { code: params[:id], timestamp: params[:timestamp], autostart: params[:autostart], captions: params[:captions] } ) %>");